#!/bin/bash
chmod +x *

echo -e "\e[34m###				  ###\e[0m"
echo -e "\e[34m#\e[0m\e[92m	EazyGit version 0.7\e[0m\e[34m	    #\e[0m"
echo -e "\e[34m#\e[0m\e[92m	 Author: Zech Bron\e[0m\e[34m	    #\e[0m"
echo -e "\e[34m#\e[0m\e[92m    https://github.com/ZechBron\e[0m\e[34m    #\e[0m"
echo -e "\e[34m###				  ###\e[0m\n"

echo -e "\e[32mPlease Choose: \e[0m"
echo -e " 1. Termux\n 2. Other"
read zCh


if [ $zCh = 1 ]; then
   cp -R eazygit $PREFIX/bin
   chmod +x $PREFIX/bin/eazygit
   eazygit
   if [ $? = 0 ]; then
      clear
      echo -e "\e[32mSuccessful\e[0m"
   elif [ $? = 1 ]; then
      echo -e "\e[91mFailed\e[0m"
   fi

elif [ $zCh = 2 ]; then
   cp -R eazygit /usr/bin
   cp -R eazygit /bin
   chmod +x /usr/bin/eazygit
   chmod +x /bin/eazygit
   eazygit
   if [ $? = 0 ]; then
      clear
      echo -e "\e[32mSuccessful\e[0m"
   elif [ $? = 1 ]; then
      sudo cp -R eazygit /usr/bin
      sudo cp -R eazygit /bin
      sudo chmod +x usr/bin/eazygit
      sudo chmod +x /bin/eazygit
      eazygit
      if [ $? = 0 ]; then
         clear
         echo -e "\e[32mDone\e[0m"
      elif [ $? = 1 ]; then
         echo -e "\e[91mUnknown Error\e[0m"
      fi
   else
      echo -e "\e[91mUnknown Error\e[0m"
   fi
else
   echo -e "\e[91mWrong input.\e[0m"
fi





